"""PDF generator for Alert Reports — dark trading terminal theme."""

from __future__ import annotations

import pandas as pd
from fpdf import FPDF

# ── Colors ───────────────────────────────────────────────────────────────

_BG = (13, 17, 23)  # #0d1117
_TEXT = (230, 237, 243)  # #e6edf3
_MUTED = (139, 148, 158)  # #8b949e
_GREEN = (63, 185, 80)  # #3fb950
_RED = (248, 81, 73)  # #f85149
_BLUE_BG = (30, 58, 95)  # #1e3a5f
_ROW_ALT = (22, 27, 34)  # #161b22
_ROW_EVEN = (13, 17, 23)  # same as BG
_BORDER = (48, 54, 61)  # #30363d
_ACCENT = (88, 166, 255)  # #58a6ff


def _score_label(score: int) -> str:
    if score >= 90:
        return "A+"
    if score >= 75:
        return "A"
    if score >= 50:
        return "B"
    return "C"


def _sanitize(text: str) -> str:
    """Replace non-latin1 characters so Helvetica doesn't choke."""
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _fmt_price(val) -> str:
    if val is None:
        return "-"
    try:
        return f"${float(val):,.2f}"
    except (ValueError, TypeError):
        return "-"


def _time_str(created: str) -> str:
    if not created:
        return ""
    try:
        return pd.Timestamp(created).strftime("%I:%M %p")
    except Exception:
        return str(created)[:16]


# ── Column definitions ───────────────────────────────────────────────────

_COLUMNS = [
    ("Time", 22),
    ("Symbol", 18),
    ("Dir", 12),
    ("Type", 24),
    ("Score", 14),
    ("Price", 20),
    ("Entry", 20),
    ("Stop", 20),
    ("T1", 20),
    ("T2", 20),
    ("Message", 87),
]

_TABLE_W = sum(w for _, w in _COLUMNS)  # should be ~277 for landscape A4


# ── PDF class ────────────────────────────────────────────────────────────


class _AlertPDF(FPDF):
    """Custom FPDF subclass with dark theme header/footer."""

    date_range: str = ""

    def header(self):
        self.set_fill_color(*_BG)
        self.rect(0, 0, self.w, self.h, "F")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*_ACCENT)
        self.cell(0, 8, "TradeSignal - Alert Report", new_x="LMARGIN", new_y="NEXT")
        if self.date_range:
            self.set_font("Helvetica", "", 9)
            self.set_text_color(*_MUTED)
            self.cell(0, 5, self.date_range, new_x="LMARGIN", new_y="NEXT")
        self.ln(3)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*_MUTED)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")
        self.set_x(self.l_margin)
        self.cell(0, 10, "Generated by TradeSignal", align="L")


# ── Public API ───────────────────────────────────────────────────────────


def generate_alerts_pdf(
    filtered: list[dict],
    summaries_by_date: dict[str, dict],
    dates: list[str],
) -> bytes:
    """Generate a styled PDF report and return raw bytes."""
    pdf = _AlertPDF(orientation="L", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Date range label
    if len(dates) == 1:
        pdf.date_range = dates[0]
    elif len(dates) > 1:
        pdf.date_range = f"{dates[-1]}  to  {dates[0]}"

    pdf.add_page()

    # ── KPI bar ──────────────────────────────────────────────────────────
    total_buy = sum(s.get("buy_count", 0) for s in summaries_by_date.values())
    total_sell = sum(s.get("sell_count", 0) for s in summaries_by_date.values())
    total_t1 = sum(s.get("t1_hits", 0) for s in summaries_by_date.values())
    total_t2 = sum(s.get("t2_hits", 0) for s in summaries_by_date.values())
    total_stopped = sum(s.get("stopped_out", 0) for s in summaries_by_date.values())

    kpis = [
        ("Total", len(filtered), _TEXT),
        ("BUY", total_buy, _GREEN),
        ("SELL", total_sell, _RED),
        ("T1 Hits", total_t1, _ACCENT),
        ("T2 Hits", total_t2, _ACCENT),
        ("Stopped", total_stopped, _RED),
    ]

    kpi_w = _TABLE_W / len(kpis)
    pdf.set_fill_color(*_ROW_ALT)

    for label, value, color in kpis:
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*_MUTED)
        x_before = pdf.get_x()
        pdf.cell(kpi_w, 5, label, align="C", fill=True)
        pdf.set_x(x_before)
        pdf.set_y(pdf.get_y() + 5)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*color)
        pdf.cell(kpi_w, 7, str(value), align="C", fill=True)
        pdf.set_xy(x_before + kpi_w, pdf.get_y() - 5)

    pdf.ln(10)

    # ── Group filtered alerts by date ────────────────────────────────────
    from collections import defaultdict

    grouped: dict[str, list[dict]] = defaultdict(list)
    for a in filtered:
        grouped[a.get("_session_date", "")].append(a)

    for session_date in dates:
        day_alerts = grouped.get(session_date, [])
        if not day_alerts:
            continue

        # ── Date header ──────────────────────────────────────────────────
        date_display = pd.Timestamp(session_date).strftime("%A, %b %d %Y")
        buy_c = sum(1 for a in day_alerts if a.get("direction") == "BUY")
        sell_c = len(day_alerts) - buy_c

        pdf.set_fill_color(*_BLUE_BG)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*_TEXT)
        header_text = f"  {date_display}  -  {len(day_alerts)} alerts  |  {buy_c} BUY  |  {sell_c} SELL"
        pdf.cell(_TABLE_W, 8, header_text, fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        # ── Table header row ─────────────────────────────────────────────
        pdf.set_fill_color(*_BORDER)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(*_TEXT)
        for col_name, col_w in _COLUMNS:
            pdf.cell(col_w, 6, col_name, border=0, fill=True, align="C")
        pdf.ln()

        # ── Alert rows ──────────────────────────────────────────────────
        for idx, alert in enumerate(day_alerts):
            bg = _ROW_ALT if idx % 2 == 0 else _ROW_EVEN
            pdf.set_fill_color(*bg)
            pdf.set_font("Helvetica", "", 7)

            direction = alert.get("direction", "")
            row_data = [
                _time_str(alert.get("created_at", "")),
                alert.get("symbol", ""),
                direction,
                alert.get("alert_type", "").replace("_", " ").title(),
                f'{_score_label(alert.get("score", 0))} ({alert.get("score", 0)})',
                _fmt_price(alert.get("price")),
                _fmt_price(alert.get("entry")),
                _fmt_price(alert.get("stop")),
                _fmt_price(alert.get("target_1")),
                _fmt_price(alert.get("target_2")),
                _sanitize(alert.get("message", "")[:80]),
            ]

            row_h = 6
            for i, ((_, col_w), val) in enumerate(zip(_COLUMNS, row_data)):
                # Color direction column
                if i == 2:
                    if direction == "BUY":
                        pdf.set_text_color(*_GREEN)
                    elif direction in ("SELL", "SHORT"):
                        pdf.set_text_color(*_RED)
                    else:
                        pdf.set_text_color(*_MUTED)
                elif i == 4:
                    # Score column coloring
                    score = alert.get("score", 0)
                    if score >= 75:
                        pdf.set_text_color(*_GREEN)
                    elif score >= 50:
                        pdf.set_text_color(210, 153, 34)
                    else:
                        pdf.set_text_color(*_MUTED)
                else:
                    pdf.set_text_color(*_TEXT)

                align = "L" if i == 10 else "C"
                pdf.cell(col_w, row_h, val, border=0, fill=True, align=align)

            pdf.ln()

        pdf.ln(4)

    return pdf.output()
